export GREP_OPTIONS='--color=auto'

alias aidan='open /Users/joepellegrino/Library/CloudStorage/GoogleDrive-jmpellegrino99@gmail.com/My\ Drive/Tutoring/Aidan\ Kelemen'
alias bl='system_profiler SPBluetoothDataType'
alias c='clear'
alias clear_downloads='rm -rf ~/Downloads/*'
alias copy_apps="ls /Applications > ~/Scripts/applications.txt; sed -i '' 's/\.app//g' ~/Scripts/applications.txt"
alias e='exit'
alias empty_trash='rm -r ~/.Trash/*'
alias fox='python3 ~/Github/linux-swashbuckling/fox.py'
alias gitpull='source ~/Github/gitpull.sh'
alias icloud='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/'
alias l='ls'
alias lsl='ls -lhS'
alias reset_launchpad='defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock'
alias size='du -sh'
alias text='open -a TextEdit'
alias tr='trans -b'
alias zip='zip -e'
alias publicip='curl ifconfig.me'
